/**
 * Sample quiz content grouped by level (1 = easiest, 5 = hardest).
 * Each entry: [question, correctAnswer, wrong1, wrong2, wrong3]
 */
export const LEVELS = [
  { rank: 1, name: 'Warm Up', prize: 100 },
  { rank: 2, name: 'Easy Street', prize: 500 },
  { rank: 3, name: 'Challenger', prize: 2500 },
  { rank: 4, name: 'Expert Zone', prize: 10000 },
  { rank: 5, name: 'Mastermind', prize: 50000 },
];

export const QUESTIONS_BY_LEVEL = {
  1: [
    ['What color is a ripe banana?', 'Yellow', 'Blue', 'Purple', 'Black'],
    ['How many days are in one week?', '7', '5', '10', '14'],
    ['What do bees produce?', 'Honey', 'Milk', 'Silk', 'Wax only'],
    ['How many wheels does a standard bicycle have?', '2', '3', '4', '1'],
    ['What is 2 + 2?', '4', '3', '5', '22'],
    ['Which animal is known for saying "moo"?', 'Cow', 'Dog', 'Cat', 'Sheep'],
    ['What is the opposite of hot?', 'Cold', 'Warm', 'Bright', 'Loud'],
    ['How many fingers are on one human hand?', '5', '4', '6', '10'],
    ['Which star provides light and heat to Earth?', 'The Sun', 'The Moon', 'Mars', 'Polaris'],
    ['What do humans breathe in to survive?', 'Oxygen', 'Helium', 'Carbon monoxide', 'Neon'],
    ['Which season comes directly after winter?', 'Spring', 'Summer', 'Autumn', 'Monsoon'],
    ['What shape has exactly three sides?', 'Triangle', 'Square', 'Circle', 'Pentagon'],
    ['What is frozen water called?', 'Ice', 'Steam', 'Fog', 'Rain'],
    ['How many months are in a calendar year?', '12', '10', '11', '13'],
    ['What color is most grass?', 'Green', 'Red', 'Orange', 'Silver'],
    ['Which fruit is commonly used in apple pie?', 'Apple', 'Banana', 'Grape', 'Mango'],
    ['What sound do cats typically make?', 'Meow', 'Woof', 'Moo', 'Oink'],
    ['How many cents are in one US dollar?', '100', '10', '50', '1000'],
    ['Which planet is called the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Neptune'],
    ['What tool do you commonly use to write on paper?', 'Pen', 'Hammer', 'Spoon', 'Brush'],
    ['How many hours are in one day?', '24', '12', '48', '36'],
  ],
  2: [
    ['What is the capital of France?', 'Paris', 'Rome', 'Madrid', 'Berlin'],
    ['Which ocean is the largest on Earth?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
    ['How many continents are there?', '7', '5', '6', '8'],
    ['What gas do plants absorb from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars'],
    ['What is the boiling point of water at sea level in °C?', '100', '0', '50', '212'],
    ['Who wrote "Romeo and Juliet"?', 'William Shakespeare', 'Charles Dickens', 'Mark Twain', 'Homer'],
    ['What is the largest mammal on Earth?', 'Blue whale', 'Elephant', 'Giraffe', 'Polar bear'],
    ['Which country is home to the kangaroo?', 'Australia', 'Brazil', 'Canada', 'India'],
    ['What is H2O commonly known as?', 'Water', 'Salt', 'Hydrogen peroxide', 'Ozone'],
    ['How many sides does a hexagon have?', '6', '5', '8', '4'],
    ['Which instrument has black and white keys?', 'Piano', 'Guitar', 'Violin', 'Flute'],
    ['What is the main language spoken in Brazil?', 'Portuguese', 'Spanish', 'French', 'Italian'],
    ['Which metal is liquid at room temperature?', 'Mercury', 'Iron', 'Gold', 'Copper'],
    ['What is the tallest mountain in the world?', 'Mount Everest', 'K2', 'Kilimanjaro', 'Mont Blanc'],
    ['Which organ pumps blood through the body?', 'Heart', 'Liver', 'Lung', 'Kidney'],
    ['What is the chemical symbol for gold?', 'Au', 'Ag', 'Fe', 'Pb'],
    ['How many players are on a soccer team on the field?', '11', '9', '10', '12'],
    ['Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin K'],
    ['What is the capital of Japan?', 'Tokyo', 'Seoul', 'Beijing', 'Bangkok'],
    ['Which bird is often associated with delivering babies in folklore?', 'Stork', 'Eagle', 'Owl', 'Crow'],
  ],
  3: [
    ['In what year did World War II end?', '1945', '1939', '1950', '1918'],
    ['What is the powerhouse of the cell?', 'Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'],
    ['Which element has the atomic number 6?', 'Carbon', 'Oxygen', 'Nitrogen', 'Helium'],
    ['Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
    ['What is the speed of light in vacuum (approx.)?', '300,000 km/s', '150,000 km/s', '30,000 km/s', '3,000 km/s'],
    ['Which empire was ruled by Julius Caesar?', 'Roman Empire', 'Greek Empire', 'Ottoman Empire', 'Persian Empire'],
    ['What is the largest desert in the world?', 'Antarctic Desert', 'Sahara Desert', 'Gobi Desert', 'Kalahari Desert'],
    ['Which blood type is known as the universal donor?', 'O negative', 'AB positive', 'A positive', 'B negative'],
    ['What language did ancient Romans primarily speak?', 'Latin', 'Greek', 'Italian', 'French'],
    ['Which scientist proposed the theory of general relativity?', 'Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['Which planet has the most moons in our solar system?', 'Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    ['What is the hardest natural substance on Earth?', 'Diamond', 'Quartz', 'Topaz', 'Graphite'],
    ['Who discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Edward Jenner'],
    ['What is the longest river in the world?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi'],
    ['Which country invented paper-making?', 'China', 'Egypt', 'Greece', 'India'],
    ['What is the chemical formula for table salt?', 'NaCl', 'KCl', 'NaOH', 'HCl'],
    ['Which war was fought between the North and South in the United States?', 'American Civil War', 'Revolutionary War', 'World War I', 'Vietnam War'],
    ['What particle carries a positive charge in an atom\'s nucleus?', 'Proton', 'Electron', 'Neutron', 'Photon'],
    ['Which composer wrote the "Fifth Symphony"?', 'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Bach', 'Franz Schubert'],
    ['What is the smallest prime number greater than 1?', '2', '1', '3', '0'],
  ],
  4: [
    ['What is the derivative of x² with respect to x?', '2x', 'x', 'x²', '2'],
    ['Which philosopher wrote "The Republic"?', 'Plato', 'Aristotle', 'Socrates', 'Descartes'],
    ['What is the half-life of Carbon-14 (approx.)?', '5,730 years', '1,200 years', '12,000 years', '500 years'],
    ['In computing, what does CPU stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Utility'],
    ['Which treaty ended World War I?', 'Treaty of Versailles', 'Treaty of Paris', 'Treaty of Tordesillas', 'Treaty of Ghent'],
    ['What is the time complexity of binary search on a sorted array?', 'O(log n)', 'O(n)', 'O(n²)', 'O(1)'],
    ['Who developed the polio vaccine widely used in the 1950s?', 'Jonas Salk', 'Edward Jenner', 'Robert Koch', 'Paul Ehrlich'],
    ['What is the capital of Kazakhstan (since 2019)?', 'Astana', 'Almaty', 'Tashkent', 'Bishkek'],
    ['Which neurotransmitter is primarily associated with pleasure and reward?', 'Dopamine', 'Serotonin', 'Acetylcholine', 'GABA'],
    ['What is the rarest blood type among the ABO system?', 'AB negative', 'O positive', 'A positive', 'B positive'],
    ['In literature, who wrote "One Hundred Years of Solitude"?', 'Gabriel García Márquez', 'Jorge Luis Borges', 'Pablo Neruda', 'Isabel Allende'],
    ['What is the SI unit of electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt'],
    ['Which ancient wonder was located in Alexandria?', 'Lighthouse of Alexandria', 'Hanging Gardens', 'Colossus of Rhodes', 'Temple of Artemis'],
    ['What algorithm is commonly used for public-key cryptography?', 'RSA', 'MD5', 'SHA-1', 'Blowfish symmetric only'],
    ['Which element is essential for hemoglobin to bind oxygen?', 'Iron', 'Calcium', 'Sodium', 'Potassium'],
    ['What year was the first iPhone released?', '2007', '2005', '2010', '2003'],
    ['Who proved Fermat\'s Last Theorem?', 'Andrew Wiles', 'Alan Turing', 'Blaise Pascal', 'Carl Gauss'],
    ['What is the deepest ocean trench on Earth?', 'Mariana Trench', 'Puerto Rico Trench', 'Java Trench', 'Peru-Chile Trench'],
    ['Which programming paradigm does Haskell primarily use?', 'Functional', 'Object-oriented', 'Procedural', 'Logic'],
    ['What is the primary export crop of Vietnam?', 'Coffee', 'Wheat', 'Corn', 'Soybeans'],
    ['In physics, what principle states that energy cannot be created or destroyed?', 'Law of Conservation of Energy', 'Newton\'s First Law', 'Bernoulli\'s Principle', 'Archimedes\' Principle'],
  ],
  5: [
    ['What is the Gödel numbering primarily used to formalize?', 'Arithmetic in logic', 'Quantum states', 'Graph coloring', 'Fluid dynamics'],
    ['Which enzyme unwinds DNA during replication?', 'Helicase', 'Ligase', 'Polymerase only', 'Primase only'],
    ['What is the exact value of Euler\'s number e (to 3 decimals)?', '2.718', '3.142', '1.618', '2.303'],
    ['Who won the Fields Medal for proving the Poincaré conjecture?', 'Grigori Perelman', 'Terence Tao', 'Edward Witten', 'Jean-Pierre Serre'],
    ['What is the chemical name for laughing gas?', 'Nitrous oxide', 'Nitric oxide', 'Nitrogen dioxide', 'Ammonia'],
    ['In number theory, what is a number divisible only by 1 and itself called?', 'Prime number', 'Composite number', 'Perfect number', 'Rational number'],
    ['Which quantum number describes orbital angular momentum?', 'l', 'n', 'm', 's only'],
    ['What year was the human genome first sequenced (draft announced)?', '2001', '1995', '2010', '1989'],
    ['Who formulated the uncertainty principle in quantum mechanics?', 'Werner Heisenberg', 'Erwin Schrödinger', 'Max Planck', 'Niels Bohr'],
    ['What is the time complexity of the Fast Fourier Transform?', 'O(n log n)', 'O(n²)', 'O(log n)', 'O(n)'],
    ['Which philosopher introduced the categorical imperative?', 'Immanuel Kant', 'David Hume', 'John Locke', 'Thomas Hobbes'],
    ['What is the molecular formula for benzene?', 'C6H6', 'C6H12', 'C7H8', 'C5H10'],
    ['In economics, what measures responsiveness of quantity demanded to price?', 'Price elasticity of demand', 'GDP deflator', 'Laffer curve', 'Gini coefficient'],
    ['Which particle was discovered at CERN in 2012?', 'Higgs boson', 'Graviton', 'Tachyon', 'Gluon only'],
    ['What is the capital city of Bhutan?', 'Thimphu', 'Kathmandu', 'Dhaka', 'Colombo'],
    ['Who wrote "Principia Mathematica" with Alfred North Whitehead?', 'Bertrand Russell', 'Gottlob Frege', 'Ludwig Wittgenstein', 'Kurt Gödel'],
    ['What is the Riemann Hypothesis primarily about?', 'Distribution of prime numbers', 'Continuity of functions', 'Topology of manifolds', 'Group theory symmetries'],
    ['Which organelle contains its own circular DNA in eukaryotes?', 'Mitochondria', 'Endoplasmic reticulum', 'Lysosome', 'Peroxisome'],
    ['What is the standard electrode potential of the SHE defined as?', '0.00 V', '1.00 V', '-1.00 V', '0.50 V'],
    ['In cryptography, what problem underlies RSA security?', 'Integer factorization', 'Discrete logarithm in elliptic curves', 'Graph isomorphism', 'Traveling salesman'],
    ['Which ancient Greek calculated the circumference of Earth remarkably accurately?', 'Eratosthenes', 'Pythagoras', 'Euclid', 'Archimedes'],
  ],
};

export function pointsForLevel(levelRank) {
  return levelRank * 10;
}
